"""add_student_password_hash

Revision ID: a79abc08abaa
Revises: 149e2824199a
Create Date: 2026-08-22 07:06:07.934937

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "a79abc08abaa"
down_revision: str | None = "149e2824199a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("students", sa.Column("password_hash", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("students", "password_hash")
    # ### end Alembic commands ###
