// This file is generated by openapi-typescript. Do not hand-edit.
// Run: pnpm --filter @statics/contract generate
//
// Phase 0 stub — only the health endpoint is defined.
// Phase 1 will expand the contract with all student and instructor routes.

export interface paths {
  "/api/v1/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getHealth"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}

export interface components {
  schemas: {
    HealthResponse: {
      status: string;
      version: string;
    };
  };
}

export interface operations {
  getHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: Record<string, never>;
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
}
