/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/student/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a student account and start a session */
        post: operations["registerStudent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/student/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate a student by PID and password */
        post: operations["loginStudent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/student/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clear the student session cookie */
        post: operations["logoutStudent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/instructor/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an instructor account and start a session */
        post: operations["registerInstructor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/instructor/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate an instructor by email and password */
        post: operations["loginInstructor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/instructor/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clear the instructor session cookie */
        post: operations["logoutInstructor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/instructor/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in instructor, resolved from the session cookie */
        get: operations["readInstructorMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/student/assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Assignments visible to the signed-in student */
        get: operations["listStudentAssignments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assignments/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get assignment summary */
        get: operations["getAssignment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assignments/{slug}/problems/{index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a problem payload for the current student */
        get: operations["getProblem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assignments/{slug}/problems/{index}/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save answers without checking */
        put: operations["saveAnswers"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assignments/{slug}/problems/{index}/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check answers against the solution */
        post: operations["checkAnswers"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assignments/{slug}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finalize and submit the assignment */
        post: operations["submitAssignment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assignments/{slug}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get submission result (only available after submit) */
        get: operations["getResult"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Courses the signed-in instructor has a role on */
        get: operations["listCourses"];
        put?: never;
        /** Create a course */
        post: operations["createCourse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/courses/{courseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Course detail */
        get: operations["getCourse"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update course metadata */
        patch: operations["updateCourse"];
        trace?: never;
    };
    "/api/v1/admin/courses/{courseId}/roster": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Roster entries for a course, claimed and unclaimed alike */
        get: operations["listRoster"];
        put?: never;
        /**
         * Add roster entries in bulk, by PID and/or email
         * @description Entries may name students who have no account yet; `studentId` stays null until an account claims the entry. Returns one result per submitted row so partial failures are visible rather than silent.
         */
        post: operations["addRosterEntries"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/courses/{courseId}/roster/{entryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change a roster entry's status (e.g. drop a student) */
        patch: operations["updateRosterEntry"];
        trace?: never;
    };
    "/api/v1/admin/courses/{courseId}/staff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Instructors and TAs with a role on the course */
        get: operations["listCourseStaff"];
        put?: never;
        /** Grant an instructor a role on the course */
        post: operations["addCourseStaff"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @example ok */
            status: string;
            /** @example 0.1.0 */
            version: string;
        };
        StudentRegisterRequest: {
            /**
             * @description Student PID (never appears in URLs or logs)
             * @example A12345678
             */
            pid: string;
            /** @example Koshik */
            firstName: string;
            /** @example Kumar */
            lastName: string;
            /** Format: password */
            password: string;
        };
        StudentLoginRequest: {
            /** @example A12345678 */
            pid: string;
            /** Format: password */
            password: string;
        };
        StudentAuthResponse: {
            student: components["schemas"]["StudentRecord"];
        };
        StudentRecord: {
            /** Format: uuid */
            id: string;
            firstName: string;
            lastName: string;
        };
        OkResponse: {
            ok: boolean;
        };
        InstructorRegisterRequest: {
            /** @example Prof. Marko */
            name: string;
            /**
             * @description Stored lowercased so lookups and roster matching agree
             * @example marko@ucsd.edu
             */
            email: string;
            /** Format: password */
            password: string;
        };
        InstructorLoginRequest: {
            /** @example marko@ucsd.edu */
            email: string;
            /** Format: password */
            password: string;
        };
        InstructorAuthResponse: {
            instructor: components["schemas"]["InstructorRecord"];
        };
        InstructorRecord: {
            /** Format: uuid */
            id: string;
            name: string;
            email: string;
        };
        /**
         * @description Ordered least- to most-privileged
         * @enum {string}
         */
        CourseRole: "reader" | "ta" | "instructor" | "owner";
        CourseSummary: {
            /** Format: uuid */
            id: string;
            /** @example MAE-008 */
            code: string;
            /** @example Fall 2026 */
            term: string;
            /** @example 001 */
            section: string;
            /** @example Statics */
            title: string;
            isArchived: boolean;
            /** @description Roster entries with status `active` */
            studentCount: number;
            /** @description Roster entries still `invited` */
            pendingInviteCount: number;
            assignmentCount: number;
            viewerRole: components["schemas"]["CourseRole"];
        };
        CourseCreateRequest: {
            code: string;
            term: string;
            /** @default 001 */
            section: string;
            title?: string;
        };
        CourseUpdateRequest: {
            title?: string;
            isArchived?: boolean;
        };
        /**
         * @description `invited` until the student accepts. Assignments only become visible at `active`.
         * @enum {string}
         */
        RosterEntryStatus: "invited" | "active" | "declined" | "dropped";
        RosterEntry: {
            /** Format: uuid */
            id: string;
            status: components["schemas"]["RosterEntryStatus"];
            /** @description Normalized; null when the entry was added by email only */
            pid: string | null;
            email: string | null;
            firstName: string | null;
            lastName: string | null;
            /** @description True once a registered account has claimed this entry. False means the student was rostered ahead of signing up. */
            hasAccount: boolean;
            /** Format: date-time */
            invitedAt: string;
            /** Format: date-time */
            acceptedAt: string | null;
        };
        RosterImportRequest: {
            entries: components["schemas"]["RosterImportEntry"][];
        };
        /** @description At least one of `pid` or `email` must be present */
        RosterImportEntry: {
            pid?: string | null;
            email?: string | null;
            firstName?: string | null;
            lastName?: string | null;
        };
        /** @enum {string} */
        RosterImportOutcome: "added" | "already_present" | "linked_existing_account" | "invalid";
        RosterImportRowResult: {
            /** @description 1-based index into the submitted entries */
            row: number;
            outcome: components["schemas"]["RosterImportOutcome"];
            pid: string | null;
            email: string | null;
            /** @description Reason, when the outcome is `invalid` */
            message: string | null;
        };
        RosterImportResult: {
            added: number;
            alreadyPresent: number;
            linked: number;
            invalid: number;
            results: components["schemas"]["RosterImportRowResult"][];
        };
        RosterEntryUpdateRequest: {
            status: components["schemas"]["RosterEntryStatus"];
        };
        CourseStaffMember: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            instructorId: string;
            name: string;
            email: string;
            role: components["schemas"]["CourseRole"];
        };
        CourseStaffAddRequest: {
            email: string;
            role: components["schemas"]["CourseRole"];
        };
        StudentAssignmentListItem: {
            slug: string;
            title: string;
            /** @enum {string} */
            status: "not_started" | "in_progress" | "submitted";
            score: {
                earned: number;
                total: number;
            } | null;
            /** Format: date-time */
            dueAt: string | null;
            problemCount: number;
        };
        AssignmentSummary: {
            slug: string;
            title: string;
            problemCount: number;
            /** @enum {string} */
            status: "not_started" | "in_progress" | "submitted";
            /** @enum {string} */
            feedbackMode: "binary" | "per_field";
            maxAttempts: number | null;
            /** Format: date-time */
            dueAt: string | null;
            /** @description True once submitted or past a hard close */
            locked: boolean;
            problems: components["schemas"]["ProblemSummary"][];
            score?: {
                earned: number;
                total: number;
            } | null;
        };
        ProblemSummary: {
            index: number;
            /** @enum {string} */
            status: "no_attempt" | "incorrect" | "correct";
            attemptCount: number;
        };
        ProblemPayload: {
            /** @enum {integer} */
            schemaVersion: 1;
            index: number;
            /** @description Drives the renderer registry (e.g. "truss") */
            problemType: string;
            prompt: components["schemas"]["Prompt"];
            /** @description Opaque to the shell — typed per problemType by the renderer */
            geometry: unknown;
            answerSchema: components["schemas"]["AnswerSchema"];
            savedAnswers: {
                [key: string]: number | null;
            };
            attemptCount: number;
            maxAttempts: number | null;
            locked: boolean;
        };
        Prompt: {
            title: string;
            body: string;
            notes: string[];
        };
        AnswerSchema: {
            groups: components["schemas"]["AnswerGroup"][];
        };
        AnswerGroup: {
            id: string;
            label: string;
            fields: components["schemas"]["AnswerField"][];
        };
        AnswerField: {
            /** @description Matches keys in savedAnswers and CheckResult.perField */
            key: string;
            /** @description Rendered label (e.g. "S₁") */
            label: string;
            /** @example F */
            unit?: string | null;
            /** @enum {string} */
            type: "number";
            /** @example 2 */
            decimals: number | null;
        };
        TrussGeometry: {
            /** @enum {integer} */
            schemaVersion: 1;
            nodes: components["schemas"]["TrussNode"][];
            members: components["schemas"]["TrussMember"][];
            supports: components["schemas"]["TrussSupport"][];
            forces: components["schemas"]["TrussForce"][];
            bounds: components["schemas"]["TrussBounds"];
        };
        TrussNode: {
            id: number;
            x: number;
            y: number;
        };
        TrussMember: {
            id: number;
            /** @description Node id */
            from: number;
            /** @description Node id */
            to: number;
            /** @example S₁ */
            label: string;
        };
        TrussSupport: {
            /** @description Node id */
            node: number;
            /** @enum {string} */
            type: "pin" | "roller";
            /** @description Rotation of support symbol in degrees (0 = base below node) */
            angleDeg: number;
        };
        TrussForce: {
            /** @description Node id */
            node: number;
            fx: number;
            fy: number;
            /** @example 3F */
            label: string;
        };
        TrussBounds: {
            xMin: number;
            xMax: number;
            yMin: number;
            yMax: number;
        };
        AnswersRequest: {
            answers: {
                [key: string]: number | null;
            };
        };
        SavedResponse: {
            /** Format: date-time */
            savedAt: string;
        };
        CheckResult: {
            correct: boolean;
            /** @description null when feedbackMode is binary */
            perField: {
                [key: string]: boolean;
            } | null;
            message: string;
            attemptCount: number;
            /** @enum {string} */
            problemStatus: "no_attempt" | "incorrect" | "correct";
        };
        SubmissionResult: {
            /** Format: date-time */
            submittedAt: string;
            score: {
                earned: number;
                total: number;
            };
            problems: {
                index: number;
                /** @enum {string} */
                status: "no_attempt" | "incorrect" | "correct";
                points: number;
            }[];
        };
    };
    responses: never;
    parameters: {
        /** @description Assignment slug (e.g. "truss-fall-2026") */
        slug: string;
        /** @description 1-based problem index within the assignment */
        index: number;
        /** @description Internal course UUID */
        courseId: string;
        /** @description Internal roster-entry UUID (never a PID — standing rule */
        entryId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    registerStudent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudentRegisterRequest"];
            };
        };
        responses: {
            /** @description Account created; session cookie set */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentAuthResponse"];
                };
            };
            /** @description An account with that PID already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    loginStudent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudentLoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated; session cookie set */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentAuthResponse"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logoutStudent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session cleared */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    registerInstructor: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstructorRegisterRequest"];
            };
        };
        responses: {
            /** @description Account created; session cookie set */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstructorAuthResponse"];
                };
            };
            /** @description An account with that email already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Malformed email or password below the minimum length */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    loginInstructor: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstructorLoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated; session cookie set */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstructorAuthResponse"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logoutInstructor: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session cleared */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    readInstructorMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current instructor */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstructorAuthResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listStudentAssignments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Assignment list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentAssignmentListItem"][];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAssignment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Assignment slug (e.g. "truss-fall-2026") */
                slug: components["parameters"]["slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Assignment summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentSummary"];
                };
            };
            /** @description Assignment not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getProblem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Assignment slug (e.g. "truss-fall-2026") */
                slug: components["parameters"]["slug"];
                /** @description 1-based problem index within the assignment */
                index: components["parameters"]["index"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Problem payload (no solution data) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemPayload"];
                };
            };
            /** @description Assignment locked (already submitted) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Problem not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    saveAnswers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Assignment slug (e.g. "truss-fall-2026") */
                slug: components["parameters"]["slug"];
                /** @description 1-based problem index within the assignment */
                index: components["parameters"]["index"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswersRequest"];
            };
        };
        responses: {
            /** @description Answers saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedResponse"];
                };
            };
            /** @description Assignment locked */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    checkAnswers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Assignment slug (e.g. "truss-fall-2026") */
                slug: components["parameters"]["slug"];
                /** @description 1-based problem index within the assignment */
                index: components["parameters"]["index"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswersRequest"];
            };
        };
        responses: {
            /** @description Check result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckResult"];
                };
            };
            /** @description Assignment locked or max attempts reached */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Problem not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    submitAssignment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Assignment slug (e.g. "truss-fall-2026") */
                slug: components["parameters"]["slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Submission result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionResult"];
                };
            };
            /** @description Already submitted (idempotent — returns same result) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionResult"];
                };
            };
        };
    };
    getResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Assignment slug (e.g. "truss-fall-2026") */
                slug: components["parameters"]["slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Submission result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionResult"];
                };
            };
            /** @description Not yet submitted */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listCourses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Course list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseSummary"][];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createCourse: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CourseCreateRequest"];
            };
        };
        responses: {
            /** @description Course created; caller becomes owner */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseSummary"];
                };
            };
            /** @description A course with that code, term and section already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCourse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Internal course UUID */
                courseId: components["parameters"]["courseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Course detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseSummary"];
                };
            };
            /** @description No such course, or caller has no role on it */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateCourse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Internal course UUID */
                courseId: components["parameters"]["courseId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CourseUpdateRequest"];
            };
        };
        responses: {
            /** @description Updated course */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseSummary"];
                };
            };
            /** @description Insufficient course role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such course */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listRoster: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Internal course UUID */
                courseId: components["parameters"]["courseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Roster entries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RosterEntry"][];
                };
            };
            /** @description No such course */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    addRosterEntries: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Internal course UUID */
                courseId: components["parameters"]["courseId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RosterImportRequest"];
            };
        };
        responses: {
            /** @description Per-row outcome */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RosterImportResult"];
                };
            };
            /** @description Insufficient course role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such course */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateRosterEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Internal course UUID */
                courseId: components["parameters"]["courseId"];
                /** @description Internal roster-entry UUID (never a PID — standing rule */
                entryId: components["parameters"]["entryId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RosterEntryUpdateRequest"];
            };
        };
        responses: {
            /** @description Updated entry */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RosterEntry"];
                };
            };
            /** @description Insufficient course role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such course or entry */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listCourseStaff: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Internal course UUID */
                courseId: components["parameters"]["courseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Staff list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseStaffMember"][];
                };
            };
            /** @description No such course */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    addCourseStaff: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Internal course UUID */
                courseId: components["parameters"]["courseId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CourseStaffAddRequest"];
            };
        };
        responses: {
            /** @description Staff member added */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseStaffMember"];
                };
            };
            /** @description Only an owner may change course staff */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such course or no instructor with that email */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description That instructor already has a role on the course */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
